sudo: required

env:
 - DIST=lucid
 - DIST=precise

before_install:
  - cp -a .pbuilderrc $HOME
  - sudo apt-get update -qq
  - sudo apt-get install pbuilder aptitude
  - sudo pbuilder create --debootstrapopts --variant=buildd

install:
  - pip install cpp-coveralls

script:
  - sudo debuild-pbuilder -us -uc

after_success:
   coveralls --gcov-options '\-lp'

os: linux
